# Generated by Django 5.2 on 2025-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tecnología'), ('sports', 'Deportes'), ('art', 'Arte'), ('science', 'Ciencia'), ('other', 'Otros')], default='other', max_length=20),
        ),
    ]
