# Generated by Django 5.2 on 2025-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('lpf', 'Liga Profesional'), ('pbn', 'Primera Nacional'), ('int', 'Internacional'), ('arg', 'Seleccion'), ('lib', 'Libertadores'), ('sud', 'Sudamericana'), ('mun', 'Mundial 2026'), ('muc', 'Mundial de Clubes'), ('other', 'Otros')], default='other', max_length=20),
        ),
    ]
